apiVersion: apps/v1
kind: Deployment
metadata:
  name: incident-creator
  labels:
    app: incident-creator
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  replicas: {{ .Values.incidentCreator.replicas | default 1 }}
  selector:
    matchLabels:
      app: incident-creator
  template:
    metadata:
      labels:
        app: incident-creator
    spec:
      containers:
        - name: incident-creator
          image: "{{ .Values.registry }}/{{ .Values.incidentCreator.image }}:{{ .Values.incidentCreator.tag }}"
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "{{ .Values.kafka.bootstrapServers }}"
            - name: KAFKA_EVENT_TOPIC
              value: "{{ .Values.kafka.topics.events }}"
            - name: KAFKA_INCIDENT_TOPIC
              value: "{{ .Values.kafka.topics.incidents }}"
            - name: KAFKA_INCIDENT_CREATOR_GROUP
              value: "incident-creator-group"
            - name: INCIDENT_WINDOW_SECONDS
              value: "60"
            - name: INCIDENT_FAILED_LOGIN_THRESHOLD
              value: "10"
          resources:
            {{- toYaml .Values.incidentCreator.resources | nindent 12 }}
