apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: log2incident-api
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: log2incident-api
  endpoints:
    - port: http
      interval: 30s
      path: /metrics
  namespaceSelector:
    matchNames:
      - default
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: log2incident-incident-creator
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: log2incident-incident-creator
  endpoints:
    - port: http
      interval: 30s
      path: /metrics
  namespaceSelector:
    matchNames:
      - default
